server:
  servlet:
    encoding:
      force-response: true
  port: 8080

spring:
  profiles:
    include:
      - db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  token:
    secret: "secretKey"